Repository TeamPLOY/Bubble_APP, pull requests merged in 2024-09, with the labels that each got.

#14 마이페이지 완성
  lib/Pages/my_page.dart
Labels: 💡 Feature

#19 이용약관 페이지 퍼블리싱 완료
  assets/img/Me.svg
  assets/img/alram_no.svg
  assets/img/alram_yes.svg
  assets/img/arrow.svg
  assets/img/arrowdown.svg
  assets/img/back.svg
  assets/img/calendar.svg
  assets/img/check.svg
  assets/img/checkblue.svg
  assets/img/checkgray.svg
  assets/img/checkicon.svg
  assets/img/checkwhite.svg
  assets/img/dropdown.svg
  assets/img/home.svg
  assets/img/setimage.svg
  lib/Components/Box/bubblebox.dart
  lib/Pages/Terms_Use.dart
Labels: 💡 Feature

#28 feat : 예약완료페이지
  assets/img/finish.png
  lib/Pages/finish.dart
Labels: 💡 Feature

#31 fix : 이미지 경로 수정
  lib/Components/Box/bubblebox.dart
  lib/Components/Box/dropdownbox.dart
  lib/Components/Footer/footer.dart
  lib/Components/Header/header.dart
  lib/Components/Header/main_header.dart
  lib/Components/Modal/check_modal.dart
  lib/Pages/Terms_Use.dart
  lib/Pages/my_page.dart
Labels: 🐞 BugFix, 📝 Modificatiob

#33 feat : font 설정 추가
  lib/theme.dart
Labels: ⚙️ Setting

#43 chore : 경로 및 파일 수정
  assets/img/finish.png
  assets/img/finish.svg
  lib/Components/Box/bubblebox.dart
  lib/Components/Button/Button.dart
  lib/Components/Footer/footer.dart
  lib/Pages/Alarm_page/Alarm_page.dart
  lib/Pages/Alarm_page/Notice_page.dart
  lib/Pages/Alarm_page/Reservation.dart
  lib/Pages/finish.dart
  lib/Pages/login_page.dart
  lib/theme.dart
Labels: 🐞 BugFix, 📝 Modificatiob

#38 feat : 3초 후 이동
  lib/Pages/finish.dart
Labels: 💡 Feature
