Repository TeamPLOY/Bubble_APP, pull requests merged in 2024-11, with the labels that each got.

#81 api env설정
  .env
  lib/Utils/api_urls.dart
  lib/Utils/cancel_post.dart
  lib/Utils/check_get.dart
  lib/Utils/email_check.dart
  lib/Utils/email_get.dart
  lib/Utils/email_post.dart
  lib/Utils/join.dart
  lib/Utils/join_reservation.dart
  lib/Utils/login_post.dart
  lib/Utils/logout.dart
  lib/Utils/machine_get.dart
  lib/Utils/machine_save.dart
  lib/Utils/maching_check.dart
  lib/Utils/notification.dart
  lib/Utils/notification_detail.dart
  lib/Utils/refresh_post.dart
  lib/Utils/reservation_get.dart
  lib/Utils/reservation_post.dart
  lib/Utils/reservation_state_get.dart
  lib/Utils/user_get.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: 💻 Accessibility

#85 style : color&font 설정 변경
  lib/app/config/app_color.dart
  lib/app/config/app_text_styles.dart
  lib/data/Functions/Formsearch.dart
  lib/data/Functions/UnderlinedText.dart
  lib/data/Functions/emailsearch.dart
  lib/data/Functions/use_text.dart
  lib/presentation/pages/alarm/alarm_page.dart
  lib/presentation/pages/alarm/notice_detail_page.dart
  lib/presentation/pages/alarm/notice_page.dart
  lib/presentation/pages/alarm/reservation_page.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/login/login_page.dart
  lib/presentation/pages/onboarding/onboarding_page.dart
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/pages/reservation/finish_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/pages/signup/signup_page.dart
  lib/presentation/pages/signup/tos_page.dart
  lib/presentation/widgets/bottom/bottom.dart
  lib/presentation/widgets/box/dropdown_box.dart
  lib/presentation/widgets/box/home_activate.dart
  lib/presentation/widgets/box/home_notice_box.dart
  lib/presentation/widgets/box/input_box.dart
  lib/presentation/widgets/box/machine_box.dart
  lib/presentation/widgets/box/notice_box.dart
  lib/presentation/widgets/box/reservation_box.dart
  lib/presentation/widgets/box/reservation_cancel_box.dart
  lib/presentation/widgets/button/alarm_button.dart
  lib/presentation/widgets/button/next_button.dart
  lib/presentation/widgets/header/main_header.dart
  lib/presentation/widgets/header/side_header.dart
  lib/presentation/widgets/modal/logout_modal.dart
  lib/presentation/widgets/modal/reservation_cancel_modal.dart
  lib/presentation/widgets/modal/reservation_check_modal.dart
  lib/presentation/widgets/modal/reservation_modal.dart
  lib/presentation/widgets/text/input_title.dart
  lib/presentation/widgets/text/message.dart
  lib/presentation/widgets/text/profile_text.dart
  lib/presentation/widgets/text/tos.dart
  lib/theme.dart
Labels: 📝 Modificatiob

#89 com 수정 완료
  lib/presentation/pages/signup/signup_page.dart
  lib/presentation/widgets/box/email_box.dart
Labels: 📝 Modificatiob

#91 예약 1학년 수정
  lib/data/models/user_model.dart
  lib/data/providers/network/apis/profile/profile_api.dart
  lib/presentation/pages/alarm/notice_page.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/bottom/bottom.dart
  lib/presentation/widgets/box/reservation_box.dart
  lib/presentation/widgets/modal/reservation_cancel_modal.dart
  lib/presentation/widgets/modal/reservation_check_modal.dart
Labels: 📝 Modificatiob, 💡 Feature

#93 온보딩 페이지 수정
  lib/presentation/pages/onboarding/onboarding_page.dart
Labels: 📝 Modificatiob

#94 예약 페이지 박스 크기 수정
  lib/presentation/pages/onboarding/onboarding_page.dart
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 📝 Modificatiob, 💡 Feature

#96 탈퇴 기능 완료
  lib/presentation/pages/deleteUser/del_page.dart
  lib/presentation/pages/deleteUser/delete_next_page.dart
  lib/presentation/pages/profile/profile_page.dart
Labels: 📬 API, 💡 Feature

#101 예약 취소 완료 비교 수정 완료
  lib/presentation/widgets/box/reservation_cancel_box.dart
Labels: 📝 Modificatiob, 💡 Feature

#95 예약 페이지 수정
  android/app/build.gradle
  lib/presentation/pages/reservation/reservation_page.dart
Labels: 📝 Modificatiob

#103 예약 페이지 api 연결 완료
  lib/data/models/reservation_model.dart
  lib/data/models/reservation_state_model.dart
  lib/data/providers/network/apis/reservation/reservation_post_api.dart
  lib/presentation/pages/alarm/reservation_page.dart
  lib/presentation/pages/reservation/reservation_backup.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/machine_box.dart
  lib/presentation/widgets/box/reservation/reservation_machinebox.dart
  lib/presentation/widgets/box/reservation/reservation_weekbox.dart
  lib/presentation/widgets/box/reservation_cancel_box.dart
Labels: 📬 API, 💡 Feature

#105 예약 페이지 수정
  lib/presentation/pages/reservation/reservation_backup.dart
  lib/presentation/pages/reservation/reservation_page.dart
Labels: 📝 Modificatiob

#106 알림 목록 수정
  lib/presentation/pages/alarm/alarm_page.dart
  lib/presentation/pages/login/login_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/reservation_cancel_box.dart
Labels: 📝 Modificatiob

#110 예약 페이지 수정
  lib/data/models/notification_notification_model.dart
  lib/data/providers/network/apis/api_url.dart
  lib/data/providers/network/apis/notice/notice_notice_api.dart
  lib/presentation/pages/alarm/alarm_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/home_notice_box.dart
  pubspec.lock
Labels: 📝 Modificatiob

#111 예약 페이지 수정
  android/app/src/main/AndroidManifest.xml
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/bottom/bottom.dart
  lib/presentation/widgets/box/home_notice_box.dart
  lib/presentation/widgets/box/reservation/reservation_machinebox.dart
  lib/presentation/widgets/box/reservation/reservation_weekbox.dart
Labels: 📝 Modificatiob

#114 예약 취소 당일 가능
  lib/presentation/pages/alarm/alarm_page.dart
  lib/presentation/widgets/box/home_notice_box.dart
  lib/presentation/widgets/box/reservation/reservation_cancel_box.dart
Labels: 🐞 BugFix

#116 fix : font 수정
  lib/presentation/pages/login/login_page.dart
  lib/presentation/widgets/box/home_activate.dart
  lib/presentation/widgets/box/home_notice_box.dart
  lib/presentation/widgets/header/main_header.dart
  lib/presentation/widgets/modal/userfull_modal.dart
Labels: 📝 Modificatiob

#119 예약 페이지 패딩 수정
  lib/presentation/pages/reservation/reservation_page.dart
Labels: 📝 Modificatiob

#121 반응형 수정
  lib/app/config/app_text_styles.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/login/login_page.dart
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/machine_box.dart
  lib/presentation/widgets/header/login_header.dart
  lib/presentation/widgets/header/main_header.dart
Labels: 📝 Modificatiob

#122 머신 박스 반응형 수정
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/img/B.svg
  assets/img/back.svg
  assets/img/sun.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/100.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/102.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/114.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/120.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/128.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/144.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/152.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/16.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/167.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/172.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/180.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/196.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/20.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/216.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/256.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/29.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/32.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/48.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/50.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/512.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/55.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/57.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/58.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/60.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/64.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/66.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/72.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/76.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/80.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/87.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/88.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/92.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Info.plist
  lib/main.dart
  lib/presentation/pages/onboarding/onboarding_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/home_activate.dart
  lib/presentation/widgets/box/home_notice_box.dart
  lib/presentation/widgets/box/machine_box.dart
  lib/presentation/widgets/box/reservation/reservation_cancel_box.dart
  lib/presentation/widgets/box/reservation/reservation_machinebox.dart
  lib/presentation/widgets/box/reservation/reservation_weekbox.dart
  lib/presentation/widgets/header/main_header.dart
  lib/presentation/widgets/header/side_header.dart
  lib/presentation/widgets/modal/reservation_cancel_modal.dart
  lib/presentation/widgets/modal/userfull_modal.dart
Labels: 📝 Modificatiob

#123 finish 아이콘 변경
  lib/presentation/pages/alarm/alarm_page.dart
  lib/presentation/pages/alarm/notice_page.dart
  lib/presentation/pages/alarm/reservation_page.dart
  lib/presentation/pages/deleteUser/delete_next_page.dart
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/pages/signup/signup_page.dart
  lib/presentation/widgets/box/machine_box.dart
  lib/presentation/widgets/box/reservation/reservation_cancel_box.dart
  lib/presentation/widgets/header/login_header.dart
  lib/presentation/widgets/header/sign_header.dart
  lib/presentation/widgets/modal/reservation_cancel_modal.dart
  lib/presentation/widgets/modal/reservation_check_modal.dart
Labels: 📝 Modificatiob

#124 Alram_page 수정
  lib/presentation/pages/alarm/alarm_page.dart
  lib/presentation/pages/alarm/notice_page.dart
  lib/presentation/pages/alarm/reservation_page.dart
  lib/presentation/widgets/box/machine_box.dart
  lib/presentation/widgets/button/alarm_button.dart
Labels: 📝 Modificatiob

#125 styled
  lib/presentation/pages/login/login_page.dart
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/input_box.dart
  lib/presentation/widgets/box/machine_box.dart
  lib/presentation/widgets/modal/reservation_cancel_modal.dart
Labels: 📝 Modificatiob

#126 머신 박스 반응형 수정
  android/gradle/wrapper/gradle-wrapper.properties
  assets/img/BUBBLE.png
  assets/img/bubble.svg
  assets/img/sun.png
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/login/login_page.dart
  lib/presentation/pages/onboarding/onboarding_page.dart
  lib/presentation/widgets/box/machine_box.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 📝 Modificatiob

#130 자동 로그인
  android/app/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  assets/img/detail.svg
  assets/img/wash.png
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/machine_box.dart
Labels: 📝 Modificatiob, 💡 Feature

#131 자동 로그인
  lib/presentation/pages/onboarding/onboarding_page.dart
Labels: 💡 Feature

#136 자동 로그인
  lib/presentation/pages/reservation/reservation_page.dart
Labels: 💡 Feature

#137 자동 로그인 완료
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  lib/data/providers/network/security_storage.dart
  lib/presentation/pages/onboarding/onboarding_page.dart
Labels: 💡 Feature

#139 로그인 자동 완성
  lib/presentation/widgets/box/machine_box.dart
Labels: 💡 Feature

#141 여자 세탁 수정
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/reservation/reservation_weekbox.dart
Labels: 📝 Modificatiob

#144 회원 탈퇴 모달 수정
  assets/img/alarm_no.svg
  assets/img/alarm_x.svg
  assets/img/alarm_yes.svg
  assets/img/back.svg
  assets/img/calendar.svg
  assets/img/eye-off.svg
  assets/img/eye.svg
  assets/img/home.svg
  assets/img/profile.svg
  lib/presentation/widgets/bottom/bottom.dart
  lib/presentation/widgets/box/password_box.dart
  lib/presentation/widgets/header/side_header.dart
  lib/presentation/widgets/modal/logout_modal.dart
  lib/presentation/widgets/modal/reservation_cancel_modal.dart
  lib/presentation/widgets/modal/userfull_modal.dart
Labels: 📝 Modificatiob

#146 ios 시스템 폰트 크기 설정과 상관없이 앱에선 고정되도록 수정 및 폰트 크기 수정
  assets/img/alarm_no.svg
  assets/img/alarm_x.svg
  assets/img/alarm_yes.svg
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/presentation/pages/deleteUser/del_page.dart
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/pages/reservation/reservation_page.dart
  lib/presentation/widgets/box/reservation/reservation_cancel_box.dart
  lib/presentation/widgets/header/side_header.dart
  pubspec.lock
  pubspec.yaml
Labels: 📝 Modificatiob

#148 로그아웃 모달 반응형으로 수정
  assets/img/calendar.svg
  lib/presentation/pages/profile/profile_page.dart
  lib/presentation/widgets/box/password_box.dart
  lib/presentation/widgets/modal/logout_modal.dart
Labels: 📝 Modificatiob

#149 글자 애니메이션
  assets/img/bubble.png
  assets/img/bubble.svg
  lib/presentation/pages/deleteUser/del_page.dart
  lib/presentation/pages/deleteUser/delete_next_page.dart
  lib/presentation/pages/home/home_page.dart
  lib/presentation/pages/onboarding/onboarding_page.dart
  lib/presentation/widgets/box/home_notice_box.dart
Labels: 📝 Modificatiob, 💡 Feature

#151 글자 애니메이션
  lib/presentation/widgets/box/home_notice_box.dart
Labels: 📝 Modificatiob

#152 회원 탈퇴 수정
  lib/presentation/pages/deleteUser/del_page.dart
  lib/presentation/pages/deleteUser/delete_next_page.dart
Labels: 📝 Modificatiob, 💡 Feature

#153 반응형 수정
  lib/presentation/widgets/box/reservation/reservation_cancel_box.dart
  pubspec.yaml
Labels: 💡 Feature
